### ISSUE TITLE
Add ability to change fonts

### ISSUE THREAD

**Issue by tkiapril** [rfgamaral/SlackUI#19]
![untitled](https://cloud.githubusercontent.com/assets/7963440/6207090/bec243e0-b5dc-11e4-96f4-14b6a2b59cbc.png)

As you can see, the default Windows font for Korean language "terribly sucks"; like someone in the design team has made some serious mistakes.
It would be great to have a feature to change fonts, or apply some custom CSSes.

**Comment by rfgamaral** [comment]
Can you please be more specific? It looks good to me. What exactly is wrong?

However, this is a wrapper around the web site, the fonts are not controlled by SlackUI. This should look exactly like Chrome displays `your-team.slack.com`. Could you post a screenshot of that side-by-side with SlackUI?

**Comment by tkiapril** [comment]
Well, the currently displaying vanilla (legacy) default font for Korean in Windows is considered aesthetically just wrong and ugly (which the font is called 굴림, or Gulim in Latin Alphabet.) Among users, it is said that Gulim font for Korean letters are as Comic Sans in Latin Alphabet. If you know the '[Comic Sans Project] (http://comicsansproject.tumblr.com/)', there is an equivalent parody blog named '[굴림계획 (Gulim Project)] (http://comicsansproject.tumblr.com/).'

Side-by-side comparison as requested:
![untitled](https://cloud.githubusercontent.com/assets/7963440/6213345/1126a3c4-b632-11e4-873b-176f7d751a48.png)

As you can see, the font on the Chrome browser left correctly displays the page with 맑은 고딕 (Malgun Gothic) which became the default Windows Korean font since Vista along with Segoe for Latin Alphabet and Meiryo for Japanese letters. However the SlackUI page on the right shows the page with Gulim font. I did not change the fonts or preferences on the Chrome browser; I use Firefox for my daily web browsing tasks.

Although the system default font has changed to Malgun Gothic a bit ago, webpages are shown with Gulim font for default on many browsers. And I coudn't grasp a reason for that. Thus, I thought it would be a nice feature if one could apply a custom css on their own (like Stylish extension, maybe?)

**Comment by rfgamaral** [comment]
I'll have to investigate this a little further but I'm afraid there's not much that I can do since that is probably controlled by CefSharp (maybe CEF 39 "fixes" this, not sure, but I'm not willing to migrate to that just yet since it's still in pre-release).

As for custom CSS, that goes beyond the scope of SlackUI. This is not a browser replacement but a wrapper around a browser instance pointing to anyone's team site. I'll see if there's a way to make SlackUI use the default Windows font just like Chrome does and fix it that way.

**Comment by tkiapril** [comment]
Thanks for considering. Please keep up the good work!

**Comment by rfgamaral** [comment]
I can't seem to debug this... I copy pasted `맑은 고딕` into my private chat with slackbot and opened the window both with SlackUI and Chrome and didn't notice any font differences as I do on your side-by-side screenshot.

Can you please post a screenshot of the Chrome "Customize fonts..." dialog (in advanced settings)?

**Comment by tkiapril** [comment]
Sure, here you go:

![untitled](https://cloud.githubusercontent.com/assets/7963440/6223853/6820f890-b6b5-11e4-9510-b10f8274fe3c.png)

Although it is in Korean, the layouts are same. Fonts written in Order: 맑은 고딕 (Malgun Gothic), 바탕 (Batang), 맑은 고딕 (Malgun Gothic), 굴림체 (GulimChe). GulimChe is a monospaced variant of Gulim.

**Comment by rfgamaral** [comment]
Just taking a guess here but maybe Chrome configured those fonts for you and CefSharp/CEF (thus, SlackUI) picked - for some reason - the other ones. I'm not really sure there's anything I can do about this. I'll probably have to create an issue within CefSharp/CEF.

**Comment by rfgamaral** [comment]
I'm closing things because I'm afraid there's nothing I can do. Upstream CEF is the one that should be aware of those default fonts for each OS version.

CefSharp (the component I use to display a web view based on the Chromium rendering engine) only inherits from that and they do not provide an interface to changes fonts so I can't mirror such functionality. And even if they did, I'm afraid that that would actually be overkill for this *simple* application (too much work for an application that might get deprecated when the official Slack client is released).

Sorry :(
