### ISSUE TITLE
Higher resolution icon

### ISSUE THREAD

**Issue by MichaelAllenMiller** [rfgamaral/SlackUI#20]
What are your thoughts on updating the icon to use a higher resolution?  For reference, here is what the current icon looks like in my task bar next to Slack's icon for the Chrome Application Shortcut.

![image](https://cloud.githubusercontent.com/assets/1903214/6231200/cc4adcf8-b68a-11e4-8435-c63ac51a9c99.png)

**Comment by rfgamaral** [comment]
I'm ok with that as long as the 16x16 icon remains the same because IMO it looks better than a shrinked icon of that version. Which is actually a common thing across Windows apps (different icons between low and high res).

But that looks a 32x32 icon, didn't I include one in the initial release? I probably screwed it up since I've always reverted my taskbar to the smaller version and never though about that use case. My bad :(

**Comment by rfgamaral** [comment]
Aaaaaaaaaaaah, I guess didn't screw up after all...

![slackui-taskbar](https://cloud.githubusercontent.com/assets/96476/6236498/ffbc40b0-b6e2-11e4-84a1-bebe62b62ffb.png)

I'm going to change it to this version instead because it's already built-in SlackUI and it's different from the official Chrome Application shortcut :)

Good?

**Comment by MichaelAllenMiller** [comment]
Looks good!

**Comment by rfgamaral** [comment]
Fixed with d5089ee031ee6e9d88d2d85b9787718ce9c0f70d.

Thanks for the suggestion.

**Comment by MichaelAllenMiller** [comment]
Thanks!
